#!/bin/bash

# TODO: import this from one place
VERSION="0.0.1"
PACKAGE="brokerchunks-front"
COMPANY="drchunks"

ENTRY_PORT=8081
CONATINER_PORT=8081
EXTERNAL_IP="192.168.0.90"

if result=$(docker inspect ${PACKAGE} 2>/dev/null); then 
	docker start ${PACKAGE}
else
	docker run -p ${ENTRY_PORT}:${CONATINER_PORT} --name ${PACKAGE} ${COMPANY}/${PACKAGE}
fi


