#!/bin/bash

# TODO: import this from one place
VERSION="0.0.1"
PACKAGE="brokerchunks-front"
COMPANY="drchunks"

ENTRY_PORT=8081
CONATINER_PORT=8081
EXTERNAL_IP="192.168.0.90"

docker run -p ${ENTRY_PORT}:${CONATINER_PORT} ${COMPANY}/${PACKAGE}:${VERSION}